pipeline {
    agent {label 'agent-1'}
    stages {
        stage('Docker build') {
            steps {
                script {
                    sh """
                    docker build -t image:1.0 ci-dockerimg
                    """
                }
            }
        }
    }
}